# Generated by Django 4.1.4 on 2022-12-27 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to=students.models.profile_picture_dir, verbose_name='profile picture')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.department')),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.level')),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
