# Generated by Django 4.1.4 on 2022-12-27 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturers', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='attendance date')),
                ('start_time', models.TimeField(auto_now_add=True, verbose_name='start time')),
                ('end_time', models.TimeField()),
                ('longitude', models.CharField(max_length=50, verbose_name='longitude')),
                ('latitude', models.CharField(max_length=50, verbose_name='latitude')),
                ('radius', models.CharField(max_length=50, verbose_name='radius')),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='course id')),
                ('lecturer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lecturers.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.CharField(max_length=50)),
                ('slot_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendanceslot', verbose_name='attendance slot')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
