# Generated by Django 4.1.4 on 2023-01-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_level_id_student_level'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceslot',
            name='department_id',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='students.department', verbose_name='department id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendanceslot',
            name='start_time',
            field=models.TimeField(verbose_name='start time'),
        ),
    ]
