# Generated by Django 4.1.4 on 2023-01-06 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_level_id_student_level'),
        ('attendance', '0003_alter_attendanceslot_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceslot',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='students.course', verbose_name='course id'),
        ),
    ]
