# Generated by Django 4.1.4 on 2023-01-06 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_level_id_student_level'),
        ('attendance', '0004_alter_attendanceslot_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='slot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendanceslot', verbose_name='attendance slot'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
