# Generated by Django 4.1.5 on 2023-02-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_attendance_performance_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceslot',
            name='status',
            field=models.CharField(choices=[('ongoing', 'ongoing'), ('elapsed', 'elapsed')], default='ongoing', max_length=50, verbose_name='status'),
        ),
    ]
