# Generated by Django 4.1.5 on 2023-03-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendanceslot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='perf',
        ),
        migrations.AddField(
            model_name='performance',
            name='performance_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
