# Generated by Django 4.1.5 on 2023-03-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_performance_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='course',
            field=models.CharField(max_length=10, verbose_name='Course'),
        ),
    ]
