# Generated by Django 4.1.4 on 2022-12-27 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.level'),
        ),
    ]
