# Generated by Django 4.1.4 on 2023-01-05 13:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_department_id_alter_student_level_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_title',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=None),
        ),
    ]
