# Generated by Django 4.1.4 on 2023-01-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_course_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='level_id',
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], default='100', max_length=5),
        ),
    ]
