# Generated by Django 4.1.4 on 2023-01-10 13:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_studentface_student_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentface',
            name='student_face',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
