# Generated by Django 4.1.5 on 2023-03-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_studentface_student_face'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course_title',
            new_name='courses',
        ),
    ]
